merge upstream/master

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -5,6 +5,7 @@ jobs:
   parameters:
     name: macOS
     vmImage: xcode9-macos10.13
+
 - template: ci/azure/posix.yml
   parameters:
     name: Linux
@@ -21,22 +22,17 @@ jobs:
   timeoutInMinutes: 90
   steps:
   - script: |
-      # XXX next command should avoid redefining the path in every step, but
-      # made the process crash as it couldn't find deactivate
-      #echo '##vso[task.prependpath]$HOME/miniconda3/bin'
+      echo '##vso[task.prependpath]$(HOME)/miniconda3/bin'
       echo '##vso[task.setvariable variable=ENV_FILE]environment.yml'
       echo '##vso[task.setvariable variable=AZURE]true'
     displayName: 'Setting environment variables'
 
   # Do not require a conda environment
-  - script: |
-      export PATH=$HOME/miniconda3/bin:$PATH
-      ci/code_checks.sh patterns
+  - script: ci/code_checks.sh patterns
     displayName: 'Looking for unwanted patterns'
     condition: true
 
   - script: |
-      export PATH=$HOME/miniconda3/bin:$PATH
       sudo apt-get install -y libc6-dev-i386
       ci/setup_env.sh
     displayName: 'Setup environment and build pandas'
@@ -44,14 +40,12 @@ jobs:
 
   # Do not require pandas
   - script: |
-      export PATH=$HOME/miniconda3/bin:$PATH
       source activate pandas-dev
       ci/code_checks.sh lint
     displayName: 'Linting'
     condition: true
 
   - script: |
-      export PATH=$HOME/miniconda3/bin:$PATH
       source activate pandas-dev
       ci/code_checks.sh dependencies
     displayName: 'Dependencies consistency'
@@ -59,42 +53,36 @@ jobs:
 
   # Require pandas
   - script: |
-      export PATH=$HOME/miniconda3/bin:$PATH
       source activate pandas-dev
       ci/code_checks.sh code
     displayName: 'Checks on imported code'
     condition: true
 
   - script: |
-      export PATH=$HOME/miniconda3/bin:$PATH
       source activate pandas-dev
       ci/code_checks.sh doctests
     displayName: 'Running doctests'
     condition: true
 
   - script: |
-      export PATH=$HOME/miniconda3/bin:$PATH
       source activate pandas-dev
       ci/code_checks.sh docstrings
     displayName: 'Docstring validation'
     condition: true
 
   - script: |
-      export PATH=$HOME/miniconda3/bin:$PATH
       source activate pandas-dev
       ci/code_checks.sh typing
     displayName: 'Typing validation'
     condition: true
 
   - script: |
-      export PATH=$HOME/miniconda3/bin:$PATH
       source activate pandas-dev
       pytest --capture=no --strict scripts
-    displayName: 'Testing docstring validaton script'
+    displayName: 'Testing docstring validation script'
     condition: true
 
   - script: |
-      export PATH=$HOME/miniconda3/bin:$PATH
       source activate pandas-dev
       cd asv_bench
       asv check -E existing
@@ -122,19 +110,21 @@ jobs:
   timeoutInMinutes: 90
   steps:
   - script: |
-      echo '##vso[task.setvariable variable=ENV_FILE]ci/deps/travis-36-doc.yaml'
+      echo '##vso[task.setvariable variable=ENV_FILE]environment.yml'
+      echo '##vso[task.prependpath]$(HOME)/miniconda3/bin'
     displayName: 'Setting environment variables'
 
   - script: |
-      export PATH=$HOME/miniconda3/bin:$PATH
       sudo apt-get install -y libc6-dev-i386
       ci/setup_env.sh
     displayName: 'Setup environment and build pandas'
 
   - script: |
-      export PATH=$HOME/miniconda3/bin:$PATH
       source activate pandas-dev
-      doc/make.py
+      # Next we should simply have `doc/make.py --warnings-are-errors`, everything else is required because the ipython directive doesn't fail the build on errors (https://github.com/ipython/ipython/issues/11547)
+      doc/make.py --warnings-are-errors | tee sphinx.log ; SPHINX_RET=${PIPESTATUS[0]}
+      grep -B1 "^<<<-------------------------------------------------------------------------$" sphinx.log ; IPY_RET=$(( $? != 1 ))
+      exit $(( $SPHINX_RET + $IPY_RET ))
     displayName: 'Build documentation'
 
   - script: |
@@ -142,6 +132,7 @@ jobs:
       git init
       touch .nojekyll
       echo "dev.pandas.io" > CNAME
+      printf "User-agent: *\nDisallow: /" > robots.txt
       git add --all .
       git config user.email "pandas-dev@python.org"
       git config user.name "pandas-docs-bot"
@@ -172,7 +163,6 @@ jobs:
       cd doc/build/html
       git remote add origin git@github.com:pandas-dev/pandas-dev.github.io.git
       git push -f origin master
-      exit 0  # FIXME this will leave the build green even if the step fails. To be removed when we are confident with this.
     displayName: 'Publish docs to GitHub pages'
     condition : |
       and(not(eq(variables['Build.Reason'], 'PullRequest')),
