WIP

diff --git a/ci/azure/posix.yml b/ci/azure/posix.yml
--- a/ci/azure/posix.yml
+++ b/ci/azure/posix.yml
@@ -24,15 +24,107 @@ jobs:
   steps:
     - script: |
         set -eux
+        # Workaround for mamba-org/mamba#488
+        rm -f /usr/local/miniconda/pkgs/cache/*.json
+        # Installing Mamba to a fresh env is much faster (5 min vs. 1 min)
+        conda create -y -n mamba-env -c conda-forge 'mamba>=0.22'
+      displayName: Install Mamba
+
+    - task: Cache@2
+      inputs:
+        key: sccache-0
+        restoreKeys: |
+          sccache-restore-0
+        path: $(Pipeline.Workspace)/.sccache
+      displayName: Sccache cache
+
+    - script: |
+        set -eux
+        sccache_version=v0.2.15
+        sccache_archive_name=sccache-$sccache_version-x86_64-apple-darwin
+        curl -L https://github.com/mozilla/sccache/releases/download/$sccache_version/$sccache_archive_name.tar.gz \
+          | tar xzf - -O $sccache_archive_name/sccache > /usr/local/bin/sccache
+        chmod +x /usr/local/bin/sccache
+        SCCACHE_IDLE_TIMEOUT=999999 SCCACHE_DIR=$(Pipeline.Workspace)/.sccache sccache --start-server
+        sccache -s
+        sccache -z
+      displayName: Setup Sccache
+
+    - script: ls -lh $(Pipeline.Workspace)/conda_pkgs || true
+      displayName: 'List packages'
+
+    - script: conda env list
+      displayName: 'conda list'
+
+    - task: Cache@2
+      inputs:
+        key: conda-11
+        restoreKeys: |
+          conda-restore-11
+        path: $(Pipeline.Workspace)/conda_pkgs
+        cacheHitVar: CONDA_CACHE_RESTORED
+      displayName: Conda download cache
+
+    - script: mkdir -p $(Pipeline.Workspace)/conda_pkgs
+      displayName: Create Conda pkgs directory
+      condition: ne(variables.CONDA_CACHE_RESTORED, 'true')
+
+    - script: echo '##vso[task.prependpath]/usr/local/miniconda/condabin'
+      displayName: 'Set conda path'
+
+    - script: |
+        set -eux
         ls -lh
         ls -lh $(Pipeline.Workspace)
         export CONDA_PKGS_DIRS=$(Pipeline.Workspace)/conda_pkgs
+
+        # TODO: GH#44980 https://github.com/pypa/setuptools/issues/2941
+        echo '  - setuptools <60' >> ${ENV_FILE}
+
+        if [ "$(uname)" == Darwin ]; then
+          # From pyarrow on MacOS
+          # ImportError: 2): Library not loaded: @rpath/libssl.1.1.dylib
+          # Referenced from: /Users/runner/miniconda3/envs/pandas-dev/lib/libthrift.0.13.0.dylib
+          # Reason: image not found
+          sed -i'' -e 's/^  - pyarrow$/  - pyarrow=6/' ${ENV_FILE}
+        fi
+
         # See https://github.com/mamba-org/mamba/issues/633
-        #time conda create -y -n mamba
-        time conda install -y -n base -c conda-forge 'mamba>=0.22'
-      displayName: Install Mamba
-      condition: ne(variables.CONDA_MAMBA_ENV_CACHE_RESTORED, 'true')
+        time conda run --no-capture-output -n mamba-env mamba create -n pandas-dev
+        time conda run --no-capture-output -n mamba-env mamba env update -n pandas-dev --file="${ENV_FILE}"
+
+        set +e
+        echo Have qt?
+        conda run -n mamba-env mamba list -n pandas-dev -f qt --json
+        echo Have pandas?
+        conda run -n mamba-env mamba list -n pandas-dev -f pandas --json
+        conda run -n mamba-env mamba run --no-capture-output -n pandas-dev pip list | grep pandas
+        set -e
+        time DISTUTILS_C_COMPILER_LAUNCHER=sccache mamba run --no-capture-output -n pandas-dev python setup.py build_ext -v -j3
+        time mamba run --no-capture-output -n pandas-dev python -m pip install --force-reinstall --no-build-isolation -e .
+        sccache -s
+      displayName: 'Setup environment and build pandas'
+
+#     - script: |
+#         mamba run --no-capture-output -n pandas-dev ci/run_tests.sh
+#       displayName: 'Test'
+
+#     - script: |
+#         pushd /tmp
+#         mamba run --no-capture-output -n pandas-dev python -c "import pandas; pandas.show_versions()"
+#         popd
+#       displayName: 'Build versions'
+
+#     - task: PublishTestResults@2
+#       condition: succeededOrFailed()
+#       inputs:
+#         failTaskOnFailedTests: true
+#         testResultsFiles: 'test-data.xml'
+#         testRunTitle: ${{ format('{0}-$(CONDA_PY)', parameters.name) }}
+#       displayName: 'Publish test results'
 
     - script: |
-        conda run --no-capture-output -n base mamba info
-      displayName: Mamba help
+        find $(Pipeline.Workspace)/conda_pkgs -maxdepth 1 -type d -iname '*-*-*_*' | xargs rm -r
+        ls $(Pipeline.Workspace)/conda_pkgs
+      displayName: 'Reduce Conda cache size'
+      condition: ne(variables.CONDA_CACHE_RESTORED, 'true')
