Commend out more jobs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -97,94 +97,94 @@ jobs:
         path: asv_bench/benchmarks.log
       if: failure()
 
-  web_and_docs:
-    name: Web and docs
-    runs-on: ubuntu-latest
-
-    concurrency:
-      group: ${{ github.ref }}-web-docs
-      cancel-in-progress: true
-
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v2
-      with:
-        fetch-depth: 0
-
-    - name: Set up pandas
-      uses: ./.github/actions/setup
-
-    - name: Build website
-      run: |
-        source activate pandas-dev
-        python web/pandas_web.py web/pandas --target-path=web/build
-    - name: Build documentation
-      run: |
-        source activate pandas-dev
-        doc/make.py --warnings-are-errors | tee sphinx.log ; exit ${PIPESTATUS[0]}
-
-    # This can be removed when the ipython directive fails when there are errors,
-    # including the `tee sphinx.log` in te previous step (https://github.com/ipython/ipython/issues/11547)
-    - name: Check ipython directive errors
-      run: "! grep -B10 \"^<<<-------------------------------------------------------------------------$\" sphinx.log"
-
-    - name: Install ssh key
-      run: |
-        mkdir -m 700 -p ~/.ssh
-        echo "${{ secrets.server_ssh_key }}" > ~/.ssh/id_rsa
-        chmod 600 ~/.ssh/id_rsa
-        echo "${{ secrets.server_ip }} ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBE1Kkopomm7FHG5enATf7SgnpICZ4W2bw+Ho+afqin+w7sMcrsa0je7sbztFAV8YchDkiBKnWTG4cRT+KZgZCaY=" > ~/.ssh/known_hosts
-      if: ${{github.event_name == 'push' && github.ref == 'refs/heads/master'}}
-
-    - name: Copy cheatsheets into site directory
-      run: cp doc/cheatsheet/Pandas_Cheat_Sheet* web/build/
-
-    - name: Upload web
-      run: rsync -az --delete --exclude='pandas-docs' --exclude='docs' web/build/ docs@${{ secrets.server_ip }}:/usr/share/nginx/pandas
-      if: ${{github.event_name == 'push' && github.ref == 'refs/heads/master'}}
-
-    - name: Upload dev docs
-      run: rsync -az --delete doc/build/html/ docs@${{ secrets.server_ip }}:/usr/share/nginx/pandas/pandas-docs/dev
-      if: ${{github.event_name == 'push' && github.ref == 'refs/heads/master'}}
-
-    - name: Move docs into site directory
-      run: mv doc/build/html web/build/docs
-
-    - name: Save website as an artifact
-      uses: actions/upload-artifact@v2
-      with:
-        name: website
-        path: web/build
-        retention-days: 14
-
-  data_manager:
-    name: Test experimental data manager
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        pattern: ["not slow and not network and not clipboard", "slow"]
-    concurrency:
-      group: ${{ github.ref }}-data_manager-${{ matrix.pattern }}
-      cancel-in-progress: true
-
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v2
-      with:
-        fetch-depth: 0
-
-    - name: Set up pandas
-      uses: ./.github/actions/setup
-
-    - name: Run tests
-      env:
-        PANDAS_DATA_MANAGER: array
-        PATTERN: ${{ matrix.pattern }}
-        PYTEST_WORKERS: "auto"
-        PYTEST_TARGET: pandas
-      run: |
-        source activate pandas-dev
-        ci/run_tests.sh
-
-    - name: Print skipped tests
-      run: python ci/print_skipped.py
+#  web_and_docs:
+#    name: Web and docs
+#    runs-on: ubuntu-latest
+#
+#    concurrency:
+#      group: ${{ github.ref }}-web-docs
+#      cancel-in-progress: true
+#
+#    steps:
+#    - name: Checkout
+#      uses: actions/checkout@v2
+#      with:
+#        fetch-depth: 0
+#
+#    - name: Set up pandas
+#      uses: ./.github/actions/setup
+#
+#    - name: Build website
+#      run: |
+#        source activate pandas-dev
+#        python web/pandas_web.py web/pandas --target-path=web/build
+#    - name: Build documentation
+#      run: |
+#        source activate pandas-dev
+#        doc/make.py --warnings-are-errors | tee sphinx.log ; exit ${PIPESTATUS[0]}
+#
+#    # This can be removed when the ipython directive fails when there are errors,
+#    # including the `tee sphinx.log` in te previous step (https://github.com/ipython/ipython/issues/11547)
+#    - name: Check ipython directive errors
+#      run: "! grep -B10 \"^<<<-------------------------------------------------------------------------$\" sphinx.log"
+#
+#    - name: Install ssh key
+#      run: |
+#        mkdir -m 700 -p ~/.ssh
+#        echo "${{ secrets.server_ssh_key }}" > ~/.ssh/id_rsa
+#        chmod 600 ~/.ssh/id_rsa
+#        echo "${{ secrets.server_ip }} ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBE1Kkopomm7FHG5enATf7SgnpICZ4W2bw+Ho+afqin+w7sMcrsa0je7sbztFAV8YchDkiBKnWTG4cRT+KZgZCaY=" > ~/.ssh/known_hosts
+#      if: ${{github.event_name == 'push' && github.ref == 'refs/heads/master'}}
+#
+#    - name: Copy cheatsheets into site directory
+#      run: cp doc/cheatsheet/Pandas_Cheat_Sheet* web/build/
+#
+#    - name: Upload web
+#      run: rsync -az --delete --exclude='pandas-docs' --exclude='docs' web/build/ docs@${{ secrets.server_ip }}:/usr/share/nginx/pandas
+#      if: ${{github.event_name == 'push' && github.ref == 'refs/heads/master'}}
+#
+#    - name: Upload dev docs
+#      run: rsync -az --delete doc/build/html/ docs@${{ secrets.server_ip }}:/usr/share/nginx/pandas/pandas-docs/dev
+#      if: ${{github.event_name == 'push' && github.ref == 'refs/heads/master'}}
+#
+#    - name: Move docs into site directory
+#      run: mv doc/build/html web/build/docs
+#
+#    - name: Save website as an artifact
+#      uses: actions/upload-artifact@v2
+#      with:
+#        name: website
+#        path: web/build
+#        retention-days: 14
+#
+#  data_manager:
+#    name: Test experimental data manager
+#    runs-on: ubuntu-latest
+#    strategy:
+#      matrix:
+#        pattern: ["not slow and not network and not clipboard", "slow"]
+#    concurrency:
+#      group: ${{ github.ref }}-data_manager-${{ matrix.pattern }}
+#      cancel-in-progress: true
+#
+#    steps:
+#    - name: Checkout
+#      uses: actions/checkout@v2
+#      with:
+#        fetch-depth: 0
+#
+#    - name: Set up pandas
+#      uses: ./.github/actions/setup
+#
+#    - name: Run tests
+#      env:
+#        PANDAS_DATA_MANAGER: array
+#        PATTERN: ${{ matrix.pattern }}
+#        PYTEST_WORKERS: "auto"
+#        PYTEST_TARGET: pandas
+#      run: |
+#        source activate pandas-dev
+#        ci/run_tests.sh
+#
+#    - name: Print skipped tests
+#      run: python ci/print_skipped.py
