WIP

diff --git a/.github/workflows/code-checks.yml b/.github/workflows/code-checks.yml
--- a/.github/workflows/code-checks.yml
+++ b/.github/workflows/code-checks.yml
@@ -57,38 +57,38 @@ jobs:
         environment-file: ${{ env.ENV_FILE }}
         cache-env: true
 
-    - name: Install node.js (for pyright)
-      uses: actions/setup-node@v2
-      with:
-        node-version: "16"
+    # - name: Install node.js (for pyright)
+    #   uses: actions/setup-node@v2
+    #   with:
+    #     node-version: "16"
 
-    - name: Install pyright
-      # note: keep version in sync with .pre-commit-config.yaml
-      run: npm install -g pyright@1.1.212
+    # - name: Install pyright
+    #   # note: keep version in sync with .pre-commit-config.yaml
+    #   run: npm install -g pyright@1.1.212
 
-    - name: Build Pandas
-      id: build
-      uses: ./.github/actions/build_pandas
+    # - name: Build Pandas
+    #   id: build
+    #   uses: ./.github/actions/build_pandas
 
-    - name: Run checks on imported code
-      run: ci/code_checks.sh code
-      if: ${{ steps.build.outcome == 'success' }}
+    # - name: Run checks on imported code
+    #   run: ci/code_checks.sh code
+    #   if: ${{ steps.build.outcome == 'success' }}
 
-    - name: Run doctests
-      run: ci/code_checks.sh doctests
-      if: ${{ steps.build.outcome == 'success' }}
+    # - name: Run doctests
+    #   run: ci/code_checks.sh doctests
+    #   if: ${{ steps.build.outcome == 'success' }}
 
-    - name: Run docstring validation
-      run: ci/code_checks.sh docstrings
-      if: ${{ steps.build.outcome == 'success' }}
+    # - name: Run docstring validation
+    #   run: ci/code_checks.sh docstrings
+    #   if: ${{ steps.build.outcome == 'success' }}
 
-    - name: Run typing validation
-      run: ci/code_checks.sh typing
-      if: ${{ steps.build.outcome == 'success' }}
+    # - name: Run typing validation
+    #   run: ci/code_checks.sh typing
+    #   if: ${{ steps.build.outcome == 'success' }}
 
-    - name: Run docstring validation script tests
-      run: pytest scripts
-      if: ${{ steps.build.outcome == 'success' }}
+    # - name: Run docstring validation script tests
+    #   run: pytest scripts
+    #   if: ${{ steps.build.outcome == 'success' }}
 
   asv-benchmarks:
     name: ASV Benchmarks
@@ -113,50 +113,50 @@ jobs:
         environment-file: ${{ env.ENV_FILE }}
         cache-env: true
 
-    - name: Build Pandas
-      id: build
-      uses: ./.github/actions/build_pandas
+    # - name: Build Pandas
+    #   id: build
+    #   uses: ./.github/actions/build_pandas
 
-    - name: Run ASV benchmarks
-      run: |
-        cd asv_bench
-        asv check -E existing
-        git remote add upstream https://github.com/pandas-dev/pandas.git
-        git fetch upstream
-        asv machine --yes
-        asv dev | sed "/failed$/ s/^/##[error]/" | tee benchmarks.log
-        if grep "failed" benchmarks.log > /dev/null ; then
-            exit 1
-        fi
-      if: ${{ steps.build.outcome == 'success' }}
+    # - name: Run ASV benchmarks
+    #   run: |
+    #     cd asv_bench
+    #     asv check -E existing
+    #     git remote add upstream https://github.com/pandas-dev/pandas.git
+    #     git fetch upstream
+    #     asv machine --yes
+    #     asv dev | sed "/failed$/ s/^/##[error]/" | tee benchmarks.log
+    #     if grep "failed" benchmarks.log > /dev/null ; then
+    #         exit 1
+    #     fi
+    #   if: ${{ steps.build.outcome == 'success' }}
 
-    - name: Publish benchmarks artifact
-      uses: actions/upload-artifact@v2
-      with:
-        name: Benchmarks log
-        path: asv_bench/benchmarks.log
-      if: failure()
+    # - name: Publish benchmarks artifact
+    #   uses: actions/upload-artifact@v2
+    #   with:
+    #     name: Benchmarks log
+    #     path: asv_bench/benchmarks.log
+    #   if: failure()
 
-  build_docker_dev_environment:
-    name: Build Docker Dev Environment
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash -l {0}
+  # build_docker_dev_environment:
+    # name: Build Docker Dev Environment
+    # runs-on: ubuntu-latest
+    # defaults:
+    #   run:
+    #     shell: bash -l {0}
 
-    concurrency:
-      # https://github.community/t/concurrecy-not-work-for-push/183068/7
-      group: ${{ github.event_name == 'push' && github.run_number || github.ref }}-build_docker_dev_environment
-      cancel-in-progress: true
+    # concurrency:
+    #   # https://github.community/t/concurrecy-not-work-for-push/183068/7
+    #   group: ${{ github.event_name == 'push' && github.run_number || github.ref }}-build_docker_dev_environment
+    #   cancel-in-progress: true
 
-    steps:
-      - name: Clean up dangling images
-        run: docker image prune -f
+    # steps:
+    #   - name: Clean up dangling images
+    #     run: docker image prune -f
 
-      - name: Checkout
-        uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
+    #   - name: Checkout
+    #     uses: actions/checkout@v2
+    #     with:
+    #       fetch-depth: 0
 
-      - name: Build image
-        run: docker build --pull --no-cache --tag pandas-dev-env .
+    #   - name: Build image
+    #     run: docker build --pull --no-cache --tag pandas-dev-env .
