Adding jobs to test output and requests post

diff --git a/.github/workflows/web_and_docs.yml b/.github/workflows/web_and_docs.yml
--- a/.github/workflows/web_and_docs.yml
+++ b/.github/workflows/web_and_docs.yml
@@ -11,6 +11,33 @@ env:
   # PATH: $HOME/miniconda3/bin:$PATH
 
 jobs:
+  display_error:
+    name: Show error
+    steps:
+      - name: Show errors
+        run: |
+          echo "Normal output"
+          echo "##vso[task.logissue type=error]This is the error, should be highlighted"
+          echo "More normal output"
+          exit 1
+
+  write_comment:
+    name: Comment
+    steps:
+
+      - name: Install dependencies
+        run: pip install requests
+
+      - name: Write the comment
+        shell: python
+        run: |
+          import os
+          url = 'https://api.github.com/repos/{repo}/issues/comments/{pr_id}'
+          url = url.format(repo=os.env['GITHUB_REPOSITORY'], pr_id=11)
+          data = {'body': 'Comment generated from GitHub actions'}
+          resp = requests.post(url, data=data)
+          resp.raise_for_status()
+
   checks:
     name: Checks
     runs-on: ubuntu-latest
